apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kheng-sovannak1879-thanakblogwesbites
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/kheng-sovannak1879-thanakblogwesbites.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: kheng-sovannak1879-thanakblogwesbites
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
